services:
  spring_boot_app:
    build:
      dockerfile: Dockerfile.dev
    container_name: sensor_log_app
    hostname: sensor_log_app
    environment:
      # JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      JAVA_DEBUG: "true"
      JAVA_DEBUG_PORT: "*:5005"
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    restart: no

volumes:
  gradle_cache: