services:
  mongodb:
    image: mongo:7.0
    container_name: sensor_log_mongodb
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: sensor_log
    command: mongod --auth
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.runCommand({ ping: 1 })\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sensor_log_network

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: sensor_log_mosquitto
    hostname: $MQTT_HOST
    ports:
      - "1883:1883"
      - "8883:8883"
    env_file: .env
    volumes:
      - ./certs:/certs
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto.passwd:/mosquitto/config/mosquitto.passwd:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    healthcheck:
      test: ["CMD", "sh", "-c", "mosquitto_pub -h ${MQTT_HOST} -p ${MQTT_PORT} --cafile /certs/ca/isrgrootx1.pem -u ${MQTT_USER} -P ${MQTT_PASS} -t healthcheck -m ok"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - sensor_log_network

  spring_boot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor_log_app
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_DATA_MONGODB_URI: $MONGO_URI
      SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: "true"
    depends_on:
      mongodb:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    networks:
      - sensor_log_network
    restart: no

volumes:
  mongodb_data:
  mosquitto_data:
  mosquitto_logs:

networks:
  sensor_log_network:
    driver: bridge
