listener 8883
allow_anonymous true
cafile /certs/chain.pem
certfile /certs/fullchain.pem
keyfile /certs/privkey.pem
require_certificate false
use_identity_as_username false
tls_version tlsv1.2
log_type error

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json