listener 8883
allow_anonymous false
password_file /mosquitto/config/mosquitto.passwd
cafile /certs/mosquitto/growsensors.duckdns.org/fullchain1.pem
certfile /certs/mosquitto/growsensors.duckdns.org/cert1.pem
keyfile /certs/mosquitto/growsensors.duckdns.org/privkey1.pem
require_certificate false
tls_version tlsv1.2