spring.application.name=sensor_log
# spring.docker.compose.enabled=true
spring.mongodb.uri=${MONGO_URI}
mqtt.host=${MQTT_HOST}
mqtt.port=${MQTT_PORT}
mqtt.client-id=${MQTT_CLIENT_ID}
mqtt.ssl-enabled=true
mqtt.username=${MQTT_USERNAME}
mqtt.password=${MQTT_PASSWORD}