vault.uri=${VAULT_INTERNAL_ADDR}
vault.pki-path=${VAULT_PKI_PATH}
vault.authentication=APPROLE
vault.app-role.role-id=${VAULT_ROLE_ID}
vault.app-role.secret-id=${VAULT_SECRET_ID}
vault.ssl.trust-store=file:/certs/docker-truststore.p12
vault.ssl.trust-store-password=${VAULT_TRUSTSTORE_PASSWORD}
vault.ssl.trust-store-type=PKCS12